service: cvs-svc-activities
configValidationMode: warn
provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  stage: dev
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'xray:PutTraceSegments'
            - 'xray:PutTelemetryRecords'
          Resource:
            - '*'

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-tracing

functions:
  main:
    handler: src/handler.handler
    events:
      - http:
          path: activities
          method: post
      - http:
          path: activities/{id}/end
          method: put
      - http:
          path: activities/update
          method: put
      - http:
          path: activities/details
          method: get
      - http:
          path: activities/open
          method: get
      - http:
          path: activities/cleanup
          method: get

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-activities
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: testerStaffId
            AttributeType: S
          - AttributeName: startTime
            AttributeType: S
          - AttributeName: activityType
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: StaffIndex
            KeySchema:
              - AttributeName: testerStaffId
                KeyType: HASH
              - AttributeName: startTime
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - parentId
                - activityType
                - testStationName
                - testStationPNumber
                - testStationEmail
                - testStationType
                - testerName
                - startTime
                - endTime
                - waitReason
                - notes
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: ActivityTypeIndex
            KeySchema:
              - AttributeName: activityType
                KeyType: HASH
              - AttributeName: startTime
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
custom:
  serverless-offline:
    port: 3007
  dynamodb:
    start:
      port: 8005
      inMemory: true
      migrate: true
      seed: true
      noStart: false
    seed:
      activities:
        sources:
          - table: cvs-local-activities
            sources: [./tests/resources/activities.json]
    stages:
      - dev
